
PROGRAM SIZE_TEST
  USE ISO_FORTRAN_ENV
  USE SPLINES
  IMPLICIT NONE
  
    REAL(KIND=REAL64) :: KNOTS
    REAL(KIND=REAL64) :: VALUES1
    REAL(KIND=REAL64) :: VALUES2
    INTEGER :: DIVISIONS
    REAL(KIND=REAL64) :: L2_OUTPUT
  
    PRINT *, 'KNOTS', SIZEOF(KNOTS)
    PRINT *, 'VALUES1', SIZEOF(VALUES1)
    PRINT *, 'VALUES2', SIZEOF(VALUES2)
    PRINT *, 'DIVISIONS', SIZEOF(DIVISIONS)
    PRINT *, 'L2_OUTPUT', SIZEOF(L2_OUTPUT)
END PROGRAM SIZE_TEST

