PROGRAM TEST
  USE ISO_FORTRAN_ENV, ONLY: REAL64
  IMPLICIT NONE

  REAL(KIND=REAL64), DIMENSION(10,2) :: A
  REAL(KIND=REAL64), DIMENSION(2) :: B
  B = (/ 1, 2 /)
  PRINT *, A
  PRINT *, B
  PRINT *, A - B
  
END PROGRAM TEST
