
PROGRAM SIZE_TEST
  USE ISO_FORTRAN_ENV
  IMPLICIT NONE
  
    INTEGER :: DIM
    INTEGER :: NUM_DVECS
    INTEGER :: SIZE_OUTPUT
  
    PRINT *, 'DIM', SIZEOF(DIM)
    PRINT *, 'NUM_DVECS', SIZEOF(NUM_DVECS)
    PRINT *, 'SIZE_OUTPUT', SIZEOF(SIZE_OUTPUT)
END PROGRAM SIZE_TEST

