!     Module generated by fmodpy for fortran file named 'TEST_ALLOC'     
!=====================================================================
MODULE TEST_ALLOC_WRAPPER
  ! Any necessary "USE" statements
  USE ISO_FORTRAN_ENV
  ! Make sure it is clear that no implicit types are used in this wrapper
  IMPLICIT NONE
  ! Any interfaces defined for "PROCEDURE" declarations
  
    
  INTERFACE
     ! Fortran interface for passing assumed shapes to non-moduled functions.
     FUNCTION ALLOCATE_MAX_LAPACK_WORK( DIM, NUM_DVECS ) RESULT(SIZE_OUTPUT)
       USE ISO_FORTRAN_ENV
       INTEGER, INTENT(IN) :: DIM
       INTEGER, INTENT(IN) :: NUM_DVECS
       INTEGER :: SIZE_OUTPUT
     END FUNCTION ALLOCATE_MAX_LAPACK_WORK
  END INTERFACE
    
    
CONTAINS
  !     Fortran wrapper for ALLOCATE_MAX_LAPACK_WORK, callable from C     
  !========================================================

   SUBROUTINE c_ALLOCATE_MAX_LAPACK_WORK( DIM, NUM_DVECS, SIZE_OUTPUT &
     &) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    INTEGER, INTENT(IN) :: DIM
    INTEGER, INTENT(IN) :: NUM_DVECS
    INTEGER :: SIZE_OUTPUT
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    SIZE_OUTPUT = ALLOCATE_MAX_LAPACK_WORK(DIM, NUM_DVECS)
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_ALLOCATE_MAX_LAPACK_WORK

END MODULE TEST_ALLOC_WRAPPER
