SUBROUTINE MM(A, B, C)
  USE ISO_FORTRAN_ENV, ONLY: REAL64
  REAL(KIND=REAL64), INTENT(IN),  DIMENSION(:,:) :: A
  REAL(KIND=REAL64), INTENT(IN),  DIMENSION(:,:) :: B
  REAL(KIND=REAL64), INTENT(OUT), DIMENSION(:,:) :: C
  REAL(KIND=REAL64) :: ALPHA, BETA
  ALPHA = 1_REAL64
  BETA = 0_REAL64
  CALL DGEMM('T', 'N', SIZE(A,2), SIZE(B,2), SIZE(A,1), &
       ALPHA, A(:,:), SIZE(A,1), B(:,:), SIZE(B,1), &
       BETA, C(:,:), SIZE(C,1))
END SUBROUTINE MM
