!     Module generated by fmodpy for fortran file named 'BOXSPLINE'     
!=====================================================================
MODULE BOXSPLINE_WRAPPER
  ! Any necessary "USE" statements
  USE REAL_PRECISION
  ! Make sure it is clear that no implicit types are used in this wrapper
  IMPLICIT NONE
  ! Any interfaces defined for "PROCEDURE" declarations
  
    
  INTERFACE
     ! Fortran interface for passing assumed shapes to non-moduled functions.
     SUBROUTINE BOXSPLEV( DVECS, DVEC_MULTS, EVAL_PTS, BOX_EVALS, ERROR )
       USE REAL_PRECISION
       REAL(KIND=R8), DIMENSION(:,:), INTENT(IN) :: DVECS
       INTEGER, DIMENSION(:), INTENT(IN) :: DVEC_MULTS
       REAL(KIND=R8), DIMENSION(:,:), INTENT(IN) :: EVAL_PTS
       REAL(KIND=R8), DIMENSION(:), INTENT(OUT) :: BOX_EVALS
       INTEGER, INTENT(OUT) :: ERROR
     END SUBROUTINE BOXSPLEV
  END INTERFACE
    
    
CONTAINS
  !     Fortran wrapper for BOXSPLEV, callable from C     
  !========================================================

   SUBROUTINE c_BOXSPLEV( DVECS_0, DVECS_1, DVECS, DVEC_MULTS_0, DVEC_&
     &MULTS, EVAL_PTS_0, EVAL_PTS_1, EVAL_PTS, BOX_EVALS_0, BOX_EVALS,&
     & ERROR ) BIND(c)
    ! This subroutine's only purpose is to call the source fortran
    !  code while also being accessible from C.
    INTEGER, INTENT(IN) :: DVECS_0
    INTEGER, INTENT(IN) :: DVECS_1
    REAL(KIND=R8), DIMENSION(DVECS_0,DVECS_1), INTENT(IN) :: DVECS
    INTEGER, INTENT(IN) :: DVEC_MULTS_0
    INTEGER, DIMENSION(DVEC_MULTS_0), INTENT(IN) :: DVEC_MULTS
    INTEGER, INTENT(IN) :: EVAL_PTS_0
    INTEGER, INTENT(IN) :: EVAL_PTS_1
    REAL(KIND=R8), DIMENSION(EVAL_PTS_0,EVAL_PTS_1), INTENT(IN) :: EVA&
         &L_PTS
    INTEGER, INTENT(IN) :: BOX_EVALS_0
    REAL(KIND=R8), DIMENSION(BOX_EVALS_0), INTENT(OUT) :: BOX_EVALS
    INTEGER, INTENT(OUT) :: ERROR
    ! Preparation code before function call (copying character arrays)
    
    ! Calling source fortran function
    CALL BOXSPLEV(DVECS, DVEC_MULTS, EVAL_PTS, BOX_EVALS, ERROR)
    ! Copying out any necessary values for return (character arrays)
    
  END SUBROUTINE c_BOXSPLEV

END MODULE BOXSPLINE_WRAPPER
