
PROGRAM SIZE_TEST
  USE REAL_PRECISION
  IMPLICIT NONE
  
    REAL(KIND=R8) :: DVECS
    INTEGER :: DVEC_MULTS
    REAL(KIND=R8) :: EVAL_PTS
    REAL(KIND=R8) :: BOX_EVALS
    INTEGER :: ERROR
  
    PRINT *, 'DVECS', SIZEOF(DVECS)
    PRINT *, 'DVEC_MULTS', SIZEOF(DVEC_MULTS)
    PRINT *, 'EVAL_PTS', SIZEOF(EVAL_PTS)
    PRINT *, 'BOX_EVALS', SIZEOF(BOX_EVALS)
    PRINT *, 'ERROR', SIZEOF(ERROR)
END PROGRAM SIZE_TEST

